CREATE DATABASE TEMP;
USE TEMP;
CREATE TABLE ACCOUNT (
	id INT PRIMARY KEY,
    name VARCHAR(255) UNIQUE,
    balance INT NOT NULL DEFAULT 0
);

-- ADD NEW COLUMN
ALTER TABLE ACCOUNT ADD interest FLOAT NOT NULL DEFAULT 0;
-- CHANGE DATATYPE
ALTER TABLE ACCOUNT MODIFY interest DOUBLE NOT NULL DEFAULT 0;
-- DESCRIBE ACCOUNT
DESC ACCOUNT_DETAILS;
-- CHANGE COULM RENAME
ALTER TABLE ACCOUNT CHANGE COLUMN interest  Saving_interest FLOAT NOT NULL DEFAULT 0;
-- DROP COLUMN
ALTER TABLE ACCOUNT DROP COLUMN Saving_interest;
-- RENAME TABLE
ALTER TABLE ACCOUNT RENAME TO ACCOUNT_DETAILS;

SELECT * FROM account;
